	// unset(av[1]);
	// pwd();
	// cd(av[1]);
	// char *pwd = ft_getenv("PWD");
	// char *oldpwd = ft_getenv("OLDPWD");
	// printf("pwd = %s, oldpwd = %s \n", pwd, oldpwd);
	// free(pwd);
	// free(oldpwd);
	// envp = handler(2, env, av[1]);
	// envp = handler(1, env, "CLE");
	// envp = handler(3, env, "CLE=lol");
	// print_lst(envp, print_env);
	// export(av[1]);
	//  envp = handler(3, env, av[1]);
	// ft_env();
    // printf("%s \n", ft_getenv("CLE="));